{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':u'Aplicativo Factura Electr\xf3nica (PyRece)',
          'size':(580, 466),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuConsultas',
             'label':u'Consultas',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuConsultasLastCBTE',
                   'label':u'\xdalt. Cbte.',
                  },
                  {'type':'MenuItem',
                   'name':'menuConsultasLastID',
                   'label':u'\xdalt. ID',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'btnAyuda', 
    'position':(480, 393), 
    'label':u'Ayuda', 
    },

{'type':'Button', 
    'name':'btnGrabar', 
    'position':(504, 4), 
    'size':(52, -1), 
    'label':u'Grabar', 
    },

{'type':'Button', 
    'name':'btnMarcarTodo', 
    'position':(292, 163), 
    'label':u'Marcar Todo', 
    'toolTip':u'Seleccionar todas las facturas', 
    },

{'type':'Button', 
    'name':'btnAutorizarLote', 
    'position':(181, 163), 
    'label':u'Autorizar Lote', 
    'toolTip':u'Obtener CAE para todas las facturas', 
    },

{'type':'Button', 
    'name':'btnPrevisualizar', 
    'position':(395, 163), 
    'label':u'Previsualizar', 
    },

{'type':'Button', 
    'name':'btnLimpiar', 
    'position':(20, 393), 
    'label':u'Limpiar', 
    },

{'type':'Button', 
    'name':'btnAutenticar', 
    'position':(20, 163), 
    'label':u'Autenticar', 
    'toolTip':u'Iniciar Sesin en la AFIP', 
    },

{'type':'TextArea', 
    'name':'txtEstado', 
    'position':(20, 234), 
    'size':(534, 152), 
    'text':u'\n', 
    },

{'type':'StaticText', 
    'name':'lblProgreso', 
    'position':(20, 194), 
    'text':u'Progreso:', 
    },

{'type':'StaticText', 
    'name':'lblEstado', 
    'position':(22, 219), 
    'text':u'Estado:', 
    },

{'type':'Button', 
    'name':'btnEnviar', 
    'position':(479, 163), 
    'label':u'Enviar', 
    'toolTip':u'Generar y enviar mails', 
    },

{'type':'Button', 
    'name':'btnExaminar', 
    'position':(370, 5), 
    'size':(69, -1), 
    'label':u'Examinar', 
    },

{'type':'TextField', 
    'name':'txtArchivo', 
    'position':(64, 7), 
    'size':(296, -1), 
    'text':u'facturas.csv', 
    },

{'type':'StaticText', 
    'name':'lblArchivo', 
    'position':(18, 9), 
    'text':u'Archivo:', 
    },

{'type':'Button', 
    'name':'btnCargar', 
    'position':(446, 4), 
    'size':(52, -1), 
    'label':u'Cargar', 
    },

{'type':'Button', 
    'name':'btnAutorizar', 
    'position':(102, 163), 
    'label':u'Autorizar', 
    'toolTip':u'Obtener CAE por cada factura', 
    },

{'type':'MultiColumnList', 
    'name':'lvwListado', 
    'position':(20, 53), 
    'size':(537, 106), 
    'backgroundColor':(255, 255, 255, 255), 
    'columnHeadings':[], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'StaticText', 
    'name':'lblFacturas', 
    'position':(18, 35), 
    'size':(117, -1), 
    'text':u'Facturas:', 
    },

{'type':'Gauge', 
    'name':'pbProgreso', 
    'position':(77, 192), 
    'size':(477, 16), 
    'layout':'horizontal', 
    'max':100, 
    'value':0, 
    },

] # end components
} # end background
] # end backgrounds
} }
