{'application':{'type':'Application',
          'name':'Template',
    'backgrounds': [
    {'type':'Background',
          'name':'bgTemplate',
          'title':u'Aplicativo Factura Electr\xf3nica (PyRece)',
          'size':(592, 487),

        'menubar': {'type':'MenuBar',
         'menus': [
             {'type':'Menu',
             'name':'menuConsultas',
             'label':u'Consultas',
             'items': [
                  {'type':'MenuItem',
                   'name':'menuConsultasLastCBTE',
                   'label':u'\xdalt. Cbte.',
                  },
                  {'type':'MenuItem',
                   'name':'menuConsultasLastID',
                   'label':u'\xdalt. ID',
                  },
              ]
             },
         ]
     },
         'components': [

{'type':'Button', 
    'name':'btnAyuda', 
    'position':(480, 393), 
    'label':'Ayuda', 
    },

{'type':'Button', 
    'name':'btnGrabar', 
    'position':(504, 4), 
    'size':(60, -1), 
    'label':'Grabar', 
    },

{'type':'Button', 
    'name':'btnMarcarTodo', 
    'position':(292, 163), 
    'label':'Marcar Todo', 
    'toolTip':'Seleccionar todas las facturas', 
    },

{'type':'Button', 
    'name':'btnAutorizarLote', 
    'position':(188, 163), 
    'label':'Autorizar Lote', 
    'toolTip':'Obtener CAE para todas las facturas', 
    },

{'type':'Button', 
    'name':'btnPrevisualizar', 
    'position':(395, 163), 
    'label':'Previsualizar', 
    },

{'type':'Button', 
    'name':'btnLimpiar', 
    'position':(20, 393), 
    'label':'Limpiar', 
    },

{'type':'Button', 
    'name':'btnAutenticar', 
    'position':(20, 163), 
    'label':'Autenticar', 
    'toolTip':'Iniciar Sesin en la AFIP', 
    },

{'type':'TextArea', 
    'name':'txtEstado', 
    'position':(20, 234), 
    'size':(534, 152), 
    'font':{'faceName': u'Sans', 'family': 'sansSerif', 'size': 8}, 
    'text':'\n', 
    },

{'type':'StaticText', 
    'name':'lblProgreso', 
    'position':(20, 194), 
    'text':'Progreso:', 
    },

{'type':'StaticText', 
    'name':'lblEstado', 
    'position':(22, 219), 
    'text':'Estado:', 
    },

{'type':'Button', 
    'name':'btnEnviar', 
    'position':(490, 163), 
    'size':(60, -1), 
    'label':'Enviar', 
    'toolTip':'Generar y enviar mails', 
    },

{'type':'Button', 
    'name':'btnExaminar', 
    'position':(370, 4), 
    'size':(69, -1), 
    'label':'Examinar', 
    },

{'type':'TextField', 
    'name':'txtArchivo', 
    'position':(74, 5), 
    'size':(296, -1), 
    'text':'facturas.csv', 
    },

{'type':'StaticText', 
    'name':'lblArchivo', 
    'position':(18, 9), 
    'text':'Archivo:', 
    },

{'type':'Button', 
    'name':'btnCargar', 
    'position':(443, 4), 
    'size':(60, -1), 
    'label':'Cargar', 
    },

{'type':'Button', 
    'name':'btnAutorizar', 
    'position':(104, 163), 
    'label':'Autorizar', 
    'toolTip':'Obtener CAE por cada factura', 
    },

{'type':'MultiColumnList', 
    'name':'lvwListado', 
    'position':(18, 53), 
    'size':(537, 106), 
    'backgroundColor':(255, 255, 255), 
    'columnHeadings':[], 
    'font':{'faceName': u'Tahoma', 'family': 'sansSerif', 'size': 8}, 
    'items':[], 
    'maxColumns':20, 
    'rules':1, 
    },

{'type':'StaticText', 
    'name':'lblFacturas', 
    'position':(18, 35), 
    'size':(117, -1), 
    'text':'Facturas:', 
    },

{'type':'Gauge', 
    'name':'pbProgreso', 
    'position':(89, 195), 
    'size':(477, 16), 
    'backgroundColor':(209, 194, 182), 
    'layout':'horizontal', 
    'max':100, 
    'value':0, 
    },

] # end components
} # end background
] # end backgrounds
} }
